services:
  postgresql:
    container_name: postgresql
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.dl/schema.sql

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    container_name: shortener
    ports:
      - 8000:8080
    restart: always
volumes:
  postgresql: