spring:
  application:
    name: url-shortener

  profiles:
    active: dev

  # DATA SOURCE
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: shortener
    password: admin
    initialization-mode: always
    continue-on-error: true

  # JPA / HIBERNATE
  jpa:
      hibernate:
        open-in-view: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        show-sql: true

server:
  include-stacktrace: ALWAYS
  port: 8080

jwt:
  expiration: 50
