spring:
  application:
    name: url-shortener

  profiles:
    active: dev

  # DATA SOURCE
  datasource:
    url: jdbc:postgresql://${HOST}:${POST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    initialization-mode: always
    continue-on-error: true

  # JPA / HIBERNATE
  jpa:
      hibernate:
        open-in-view: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        show-sql: true

server:
  include-stacktrace: ALWAYS
  port: 8080

jwt:
  secret: ${SECRET_JWT}
  expiration: 3600000 # 1 hora en milisegundos
  refresh-expiration: 86400000 # 1 día en milisegundos

cors:
  enabled: ${CORS_ENABLED:true}